# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Livrados.com"
description: > # this means to ignore newlines until "email:"
   A Plataforma Online de Compra Colaborativa de Livros

markdown: kramdown
email: ejunior.batista@gmail.com
#blog logo
logo: "/assets/images/logo-square.png"
bars: "/assets/images/bars.png"
# blog cover
cover: "/assets/images/cover.jpg"
footer_image: "/assets/images/banner4.jpg"

name: 'Livrados.com'
author: 'Edson Ferreira Júnior'
author_image: "/assets/images/author.png"
author_bio: >
  CEO do Livrados.com, Full Stack Developer e apaixonado por livros desde sempre, criou a plataforma Livrados.com para facilitar o acesso aos livros e difundir esse amor pela leitura com o maior número de pessoas possível.

paginate:	5

url: "http://ebfjunior.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
# twitter_handle: '@dirkfabisch'
permalink: /:title/
#fill in disqus shortname to use disqus
disqus: livrados

# social icons and sharing options
social:
 # - icon:	twitter
 #   url:	https://twitter.com/dirkfabisch
 #   desc: Follow me on twitter
 #   share_url: http://twitter.com/share
 #   share_title: ?text=
 #   share_link: "&amp;url="

 - icon:	facebook
   url:	https://facebook.com/livrados
   desc: Siga a nossa página no Facebook
   share_url: https://www.facebook.com/sharer.php
   share_title: ?t=
   share_link: "&amp;u="

  # - icon:	github
  #   url:	https://github.com/dirkfabisch
  #   desc:	Fork me on github
  #   share_url:
  #   share_title:
  #   share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
